SELECT 
    DATENAME(MONTH, OrderDate),
    Sales,
    -- Running Total
    SUM(Sales) OVER(ORDER BY DATENAME(MONTH, OrderDate) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    -- Rolling Total
    SUM(Sales) OVER(ORDER BY DATENAME(MONTH, OrderDate) ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
FROM Sales.Orders;


SELECT 
    FORMAT(OrderDate, 'MMM'),
    Sales,
    SUM(Sales) OVER(ORDER BY FORMAT(OrderDate, 'MMM') ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
    SUM(Sales) OVER(ORDER BY FORMAT(OrderDate, 'MMM') ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
FROM Sales.Orders;